src/Weihnachtsmarkt/Models/Persons/RemovePersonFromShiftViewModel.cs
using Weihnachtsmarkt.Infrastructure.Dtos;

namespace Weihnachtsmarkt.Models.Persons
{
    public class RemovePersonFromShiftViewModel
    {
        public ShiftData Shift { get; set; }
        public WorkerData Worker { get; set; }
        public string ErrorMessage { get; set; }
    }
}

src/Weihnachtsmarkt/Controllers/RemovePersonFromShiftController.cs
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Weihnachtsmarkt.Infrastructure.Repositories.Interfaces;
using Weihnachtsmarkt.Models.Persons;
using Weihnachtsmarkt.Providers;
using Weihnachtsmarkt.Services;

namespace Weihnachtsmarkt.Controllers
{
    public class RemovePersonFromShiftController : Controller
    {
        private readonly IRemovePersonFromShiftViewModelProvider _removePersonFromShiftViewModelProvider;
        private readonly IBookedShiftsRepository _bookedShiftsRepository;
        private readonly IAuthenticationService _authenticationService;

        public RemovePersonFromShiftController(
            IRemovePersonFromShiftViewModelProvider removePersonFromShiftViewModelProvider, 
            IBookedShiftsRepository bookedShiftsRepository,
            IAuthenticationService authenticationService)
        {
            _removePersonFromShiftViewModelProvider = removePersonFromShiftViewModelProvider;
            _bookedShiftsRepository = bookedShiftsRepository;
            _authenticationService = authenticationService;
        }

        public async Task<ActionResult> Index(int shiftId, int workerId)
        {
            if (!_authenticationService.IsLoggedIn())
            {
                return Unauthorized();
            }

            var viewModel = await _removePersonFromShiftViewModelProvider.Provide(shiftId, workerId);
            return View(viewModel);
        }

        public async Task<ActionResult> Confirm(int shiftId, int workerId)
        {
            if (!_authenticationService.IsLoggedIn())
            {
                return Unauthorized();
            }

            try
            {
                await _bookedShiftsRepository.DeleteAsync(shiftId, workerId);
                return Redirect("~/Persons");
            }
            catch(Exception ex)
            {
                return View("Index", new RemovePersonFromShiftViewModel
                {
                    ErrorMessage = ex.Message
                });
            }
        }

        private ActionResult Unauthorized()
        {
            Response.StatusCode = (int)HttpStatusCode.Unauthorized;
            return Content(HttpStatusCode.Unauthorized + ": You must be logged in to perform this action", "text/plain");
        }
    }
}

src/Weihnachtsmarkt/Views/RemovePersonFromShift/Index.cshtml
@model Weihnachtsmarkt.Models.Persons.RemovePersonFromShiftViewModel

<h1>Schichteintrag entfernen</h1>

@{

    if (Model == null)
    {
        return;
    }

    if (!string.IsNullOrWhiteSpace(Model.ErrorMessage))
    {
        <p>Beim entfernen ist ein unerwarteter Fehler aufgetreten. Bitte versuchen Sie es erneut.</p>
        <div class="error-container">
            <div class="error-content">
                @Html.Raw(Model.ErrorMessage)
            </div>
        </div>
        return;
    }

    if (Model.Shift == null)
    {
        <h3>Es wurde keine Schicht ausgewält. Bitte versuchen Sie es erneut</h3>
        <hr />
        <p>Zurück zu <a href="~/Persons">Personen</a></p>
        return;
    }

    if (Model.Worker == null)
    {
        <h3>Diese Person wurde nicht gefunden. Bitte versuchen Sie es erneut</h3>
        <hr />
        <p>Zurück zu <a href="~/Persons">Personen</a></p>
        return;
    }

    var shift = Model.Shift;
    var worker = Model.Worker;
}

<h3>@worker.FirstName @worker.LastName von der Schicht entfernen</h3>

<table class="table">
    <tr>
        <td>Schicht Nummer</td>
        <td>@shift.ShiftId</td>
    </tr>
    <tr>
        <td>Tag</td>
        <td>@shift.ShiftStart.ToString("dddd"), @shift.ShiftStart.ToString("dd.MM")</td>
    </tr>
    <tr>
        <td>Zeitraum</td>
        <td>@shift.ShiftStart.ToString("HH:mm") Uhr - @shift.ShiftEnd.ToString("HH:mm") Uhr</td>
    </tr>
    <tr>
        <td>Anzahl benötigter Personen</td>
        <td>@shift.NeededWorkers</td>
    </tr>
    @if (shift.Workers != null && shift.Workers.Any())
    {
        <tr>
            <td>Eingetrage Personen</td>
            <td>
                @foreach (var w in shift.Workers)
                {
                    <div class="worker">
                        @w.FirstName @w.LastName
                    </div>
                }
            </td>
        </tr>
    }
</table>

<p>Möchten Sie @worker.FirstName @worker.LastName von der Schicht entfernen?</p>
<a href="~/Persons" class="btn btn-abort">Abbrechen</a>
@Html.ActionLink("Entfernen", "Confirm", "RemovePersonFromShift", new { shiftId = shift.ShiftId, workerId = worker.Id }, new { @class = "btn"})