src/Weihnachtsmarkt/Models/BookShiftViewModel.cs
using Weihnachtsmarkt.Infrastructure.Dtos;

namespace Weihnachtsmarkt.Models
{
    public class BookShiftViewModel
    {
        public ShiftData ShiftData { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public BookShiftResultViewModel ResultViewModel { get; set; }
    }
}

src/Weihnachtsmarkt/Controllers/BookShiftController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Weihnachtsmarkt.Infrastructure.Dtos;
using Weihnachtsmarkt.Infrastructure.Repositories.Interfaces;
using Weihnachtsmarkt.Infrastructure.Services.Interfaces;
using Weihnachtsmarkt.Models;
using Weihnachtsmarkt.Providers.Interfaces;

namespace Weihnachtsmarkt.Controllers
{
    public class BookShiftController : Controller
    {
        private readonly IBookShiftViewModelProvider _bookShiftViewModelProvider;
        private readonly IWorkerRepository _workerRepository;
        private readonly IBookedShiftsRepository _bookedShiftsRepository;
        private readonly IShiftService _shiftService;

        public BookShiftController(
            IBookShiftViewModelProvider bookShiftViewModelProvider, 
            IWorkerRepository workerRepository, 
            IBookedShiftsRepository bookedShiftsRepository,
            IShiftService shiftService)
        {
            _bookShiftViewModelProvider = bookShiftViewModelProvider;
            _workerRepository = workerRepository;
            _bookedShiftsRepository = bookedShiftsRepository;
            _shiftService = shiftService;
        }

        public async Task<ActionResult> Index(int? shiftId)
        {
            if (!shiftId.HasValue || shiftId.Value == 0)
            {
                return View();
            }

            var viewModel = await _bookShiftViewModelProvider.Provide(shiftId.Value);
            return View(viewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Index(BookShiftViewModel viewModel, int shiftId)
        {
            var resultViewModel = new BookShiftResultViewModel
            {
                ShiftData = await _shiftService.GetShiftWithWorkersAsync(shiftId)
            };

            viewModel.ResultViewModel = resultViewModel;
            viewModel.ShiftData = resultViewModel.ShiftData;

            if (resultViewModel.ShiftData.Workers.Count() >= resultViewModel.ShiftData.NeededWorkers)
            {
                resultViewModel.Message = "Die Schicht ist bereits voll.";
                return View(viewModel);
            }

            if (string.IsNullOrWhiteSpace(viewModel?.FirstName) || string.IsNullOrWhiteSpace(viewModel.LastName))
            {
                resultViewModel.Message = "Bitte geben Sie Ihren vollständigen Vor- und Nachnamen an.";
                return View(viewModel);
            }

            var worker = new WorkerData
            {
                FirstName = viewModel.FirstName,
                LastName = viewModel.LastName
            };

            var workerId = await _workerRepository.InsertIfNotExistsAsync(worker);

            if (await _bookedShiftsRepository.FetchAsync(shiftId, workerId) != null)
            {
                resultViewModel.Message = "Sie sind bereits in dieser Schicht eingetragen";
                return View(viewModel);
            }

            var bookedShift = new BookedShiftData
            {
                Shift = new ShiftData { ShiftId = shiftId },
                Worker = new WorkerData { Id = workerId }
            };

            await _bookedShiftsRepository.InsertAsync(bookedShift);

            resultViewModel.Success = true;

            return View(viewModel);

        }
    }
}

src/Weihnachtsmarkt/Views/BookShift/Index.cshtml
@model Weihnachtsmarkt.Models.BookShiftViewModel

@{
    if (Model?.ShiftData == null)
    {
        <h1>Bitte wählen Sie eine Schicht aus!</h1>
        <p>Zurück zur <a href="~/">Startseite</a></p>
        return;
    }

    var shift = Model.ShiftData;
    var date = shift.ShiftStart;

    if (shift.Workers.Count() >= shift.NeededWorkers)
    {
        <h1>Diese Schicht ist bereits voll!</h1>
        <p>Diese Schicht ist bereits von den folgenden Personen besetzt:</p>
        <ul>
            @foreach (var worker in shift.Workers)
            {
                <li>@worker.FirstName @worker.LastName</li>
            }
        </ul>
        <p>Da diese Schicht nur @shift.NeededWorkers Personen benötigt, kann sich niemand mehr eintragen. Bitte suchen Sie sich auf der <a href="~/">Startseite</a> eine andere Schicht raus</p>
        return;
    }
}

@if (Model.ResultViewModel != null)
{
    @Html.Partial("_Result", Model.ResultViewModel)
}

<h1>Schicht eintragen</h1>
<h3>@date.ToString("dddd"), @date.ToString("dd.MM.yyyy") @shift.ShiftStart.ToString("HH:mm") Uhr - @shift.ShiftEnd.ToString("HH:mm") Uhr</h3>
<br />
<table class="table">
    <tr>
        <td>Datum</td>
        <td>@date.ToString("dd.MM.yyyy")</td>
    </tr>
    <tr>
        <td>Uhrzeit</td>
        <td>@shift.ShiftStart.ToString("HH:mm") Uhr - @shift.ShiftEnd.ToString("HH:mm") Uhr</td>
    </tr>
    <tr>
        <td>Tätigkeit</td>
        <td>@shift.ShiftDescription</td>
    </tr>
    @if (shift.Workers != null && shift.Workers.Any())
    {
        <tr>
            <td>Bereits eingetragene Personen</td>
            <td>
                @foreach (var worker in shift.Workers)
                {
                    <div class="worker">@worker.FirstName @worker.LastName</div>
                }
            </td>
        </tr>
    }
</table>
<br />
@using (Html.BeginForm("Index", "BookShift", new { shiftId = shift.ShiftId }, FormMethod.Post))
{
    @Html.Hidden("ShiftData", Model.ShiftData)

    <div class="form-element">
        <label for="firstname">Vorname</label>
        @Html.TextBoxFor(x => x.FirstName)
    </div>

    <div class="form-element">
        <label for="lastname">Nachname</label>
        @Html.TextBoxFor(x => x.LastName)
    </div>


    <input style="float: right;" class="btn" type="submit" value="Speichern" />
}

src/Weihnachtsmarkt/Views/BookShift/_Result.cshtml
@model Weihnachtsmarkt.Models.BookShiftResultViewModel

@{
    if (Model == null)
    {
        return;
    }
}

@if (Model.Success)
{
    <div class="alert alert-success" role="alert">
        <h4>Erfolgreich!</h4>
        <p>Sie wurden erfolgreich in die Schicht eingetragen.</p>
        <hr>
        <p>Falls Sie noch in anderen Schichten mitarbeiten möchten, können Sie auf der <a href="~/">Startseite</a> nach weiteren Schichten suchen.</p>
    </div>
}
else
{
    <div class="alert alert-danger" role="alert">
        <h4>Fehler!</h4>
        <p>Beim eintragen in die Schicht ist ein Fehler aufgetreten.</p>
        <hr/>
        <p>@Model.Message</p>
    </div>
}