src/Weihnachtsmarkt/Controllers/DataProtectionController.cs
using System.Web.Mvc;

namespace Weihnachtsmarkt.Controllers
{
    public class DataProtectionController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/Weihnachtsmarkt/Controllers/LoginController.cs
using System.Configuration;
using System.Web.Mvc;
using Weihnachtsmarkt.Models;
using Weihnachtsmarkt.Services;

namespace Weihnachtsmarkt.Controllers
{
    public class LoginController : Controller
    {
        private readonly IAuthenticationService _authenticationService;

        public LoginController(IAuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }

        public ActionResult Index()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        public ActionResult Index(LoginViewModel viewModel)
        {
            if (viewModel == null)
            {
                return null;
            }

            var passwordCorrect = _authenticationService.IsPasswordCorrect(viewModel.Password);

            if (passwordCorrect)
            {
                _authenticationService.Login();
                return RedirectToAction("Index", "Home");
            }

            return View(new LoginViewModel
            {
                WrongPassword = true
            });

        }


        public ActionResult Logout()
        {
            if (_authenticationService.IsLoggedIn())
            {
                _authenticationService.Logout();
            }

            return RedirectToAction("Index", "Home");

        }
    }
}

src/Weihnachtsmarkt/Controllers/PersonsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Weihnachtsmarkt.Infrastructure.Services.Interfaces;
using Weihnachtsmarkt.Providers.Interfaces;

namespace Weihnachtsmarkt.Controllers
{
    public class PersonsController : Controller
    {
        private readonly IPersonsViewModelProvider _personsViewModelProvider;
        private readonly IShiftService _shiftService;

        public PersonsController(IPersonsViewModelProvider personsViewModelProvider, IShiftService shiftService)
        {
            _personsViewModelProvider = personsViewModelProvider;
            _shiftService = shiftService;
        }

        public async Task<ActionResult> Index()
        {
            var viewModel = await _personsViewModelProvider.Provide();
            return View(viewModel);
        }
    }
}

src/Weihnachtsmarkt/Views/Shared/_Layout.cshtml
@using Weihnachtsmarkt.Constatns
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Simon Nagel"/>

    <title>Weihnachtsmarkt</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Weihnachtsmarkt Schichtenplan", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Schichten", "Index", "Home")</li>
                    <li>@Html.ActionLink("Personen", "Index", "Persons")</li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    @if (Session[SessionKeys.LoggedIn]?.ToString() == "true")
                    {
                        <li>@Html.ActionLink("Abmelden", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Anmelden", "Index", "Login")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="main-content">
            @if (Session[SessionKeys.LoggedOut]?.ToString() == "true")
            {
                Session.Clear();
                <div class="alert alert-success" role="alert">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <h4>Erfolgreich!</h4>
                    <p>Sie wurden erfolgreich abgemeldet.</p>
                </div>
            }
            @RenderBody()
        </div>
    </div>

    <footer>
        <div class="footer-container">
            @Html.ActionLink("Impressum", "Index", "Impressum")
            @Html.ActionLink("Datenschutzerklärung", "Index", "DataProtection")
        </div>
    </footer>

@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>