src/Weihnachtsmarkt/Models/ShiftImportViewModel.cs
using Weihnachtsmarkt.Import.Dtos;

namespace Weihnachtsmarkt.Models
{
    public class ShiftImportViewModel
    {
        public ShiftImportResult Result { get; set; }
    }
}

src/Weihnachtsmarkt/Controllers/ShiftImportController.cs
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Weihnachtsmarkt.Import.Services;
using Weihnachtsmarkt.Models;
using Weihnachtsmarkt.Services;

namespace Weihnachtsmarkt.Controllers
{
    public class ShiftImportController : Controller
    {
        private readonly IShiftImportService _shiftImportService;
        private readonly IAuthenticationService _authenticationService;

        public ShiftImportController(IShiftImportService shiftImportService, IAuthenticationService authenticationService)
        {
            _shiftImportService = shiftImportService;
            _authenticationService = authenticationService;
        }
        public ActionResult Index()
        {
            if (!_authenticationService.IsLoggedIn())
            {
                return Unauthorized();
            }

            return View();
        }

        public async Task<ActionResult> ShiftImportResult()
        {
            if (!_authenticationService.IsLoggedIn())
            {
                return Unauthorized();
            }

            var model = new ShiftImportViewModel
            {
                Result = await _shiftImportService.ImportAsync()
            };

            return View(model);

        }

        private ActionResult Unauthorized()
        {
            Response.StatusCode = (int)HttpStatusCode.Unauthorized;
            return Content(HttpStatusCode.Unauthorized + ": You must be logged in to perform this action", "text/plain");
        }
    }
}

src/Weihnachtsmarkt/Views/ShiftImport/Index.cshtml
<div>
    <h1>Schichten Import</h1>
    <h3>Diese Seite ist nur für Administratoren der Seite</h3>
    <p>Auf dieser Seite wird der Import der Schichten in die Datenbank ausgeführt. Legen Sie dazu eine Datei mit dem richtigen Inhalt ab unter /wwwroot/assets/shift_import.csv</p>
    <hr/>
    <input type="button" value="Import" onclick="location.href='@Url.Action("ShiftImportResult", "ShiftImport")'" />
</div>

src/Weihnachtsmarkt/Views/ShiftImport/ShiftImportResult.cshtml
@model Weihnachtsmarkt.Models.ShiftImportViewModel

@{
    if (Model == null)
    {
        return;
    }

    var success = Model.Result.Success;
    var title = success ? "Import erfolgreich" : "Import fehlgeschlagen";
    var subtitle = success ? "Der Import wurde erfolgreich durchgeführt." : "Beim Import ist ein Fehler aufgetreten.";

}

<div class="shift-import-result-page">
    <h1>@title</h1>
    <h3>@subtitle</h3>
    <hr/>
    <div class="error-container">
        <div class="error-content">
            @Html.Raw(@Model.Result.Message)
        </div>
    </div>
</div>